# Generated by Django 5.1.7 on 2025-03-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_technician_alter_machine_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField()),
                ('maintenance_description', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technician')),
            ],
        ),
    ]
