# Generated by Django 5.1.7 on 2025-03-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_technician_email_alter_technician_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.machine'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.technician'),
        ),
    ]
